### ISSUE TITLE
Bargain Stocks feature request: detect if Cheaper by the Dozen is active

### ISSUE THREAD

**Issue by cookies1994** [Meerca/Neopets-Userscripts#3]
look for 10NP options when cheaper by the dozen banner is active in css coding?

**Comment by hiddenist** [comment]
I'd be happy to add this, but I'm not sure what the page looks like when this is active. I can add a setting  on the page to let you change the minimum amount it's looking for though, for now

**Comment by cookies1994** [comment]
That would work!

And a sort low to high on the buy side

**Comment by hiddenist** [comment]
@cookies1994 Not sure if you use the script, but I finally got Cheaper by the Dozen on my account and added detection to it! If you're interested, you can update to the current version to have it show you 10 NP stocks now.
